# Site settings
title: radiospiel.org
email: contact@radiospiel.org
description: > # this means to ignore newlines until "baseurl:"
  Hey ho!
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://radiospiel.org"
twitter_username: radiospiel
github_username:  radiospiel

# Build settings
# markdown: kramdown
markdown: redcarpet
